apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: d34m31qty-nodejs-gitops
  description: This is GitOps manifest for d34m31qty-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=d34m31qty-nodejs
    backstage.io/kubernetes-id: d34m31qty-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: d34m31qty-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:d34m31qty-nodejs
